#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"

if [ "$#" -eq  "0" ]; then
 	profile=default
else
 	profile=$1
fi

cd "$DIR"

# find poetry
POETRY=""
if [ -x /usr/bin/poetry ]; then
    POETRY=/usr/bin/poetry
elif [ -x /usr/local/bin/poetry ]; then
    POETRY=/usr/local/bin/poetry
elif [ -x ~/.local/bin/poetry ]; then
    POETRY=~/.local/bin/poetry
fi

if [ -z "$POETRY" ]; then
    echo "Poetry not found"
    exit 1
fi

# install dependencies
$POETRY run python "$DIR/launcher.py" "$profile" 

