#!/usr/bin/env python
from __future__ import print_function
import threading
import time
import socket
import sys
import signal
from termcolor import colored

from python.player import PlayerAbstract
from python.osc import OscInterface

mpvPath = '/tmp/mpvsocket'
oscPortIN = 4000
oscPortOUT = 4001

isRunning = True

# CTR-C Handler
def signal_handler(signal, frame):
        print (colored('You pressed Ctrl+C!','yellow'))
        global isRunning
        isRunning = False
signal.signal(signal.SIGINT, signal_handler)


if __name__ == '__main__':

    print()
    name = "HPlayer2"
    nameP = colored(name,'green')
    print(nameP,"started. Welcome !");

    # PLAYER Abstraction
    player = PlayerAbstract(name='j0nny', playerType='mpv')

    # OSC interface
    osc = OscInterface(oscPortIN, oscPortOUT, player)


    # RUN
    while osc.isRunning() and player.isRunning() and isRunning:
        time.sleep(1)

    # STOP
    print(nameP,"is closing..")
    if player.isRunning(): player.quit()
    if osc.isRunning(): osc.quit()

    print(nameP,"stopped. Goodbye !");
    print()
    sys.exit(0)
